runtime: python3.7


handlers:
  - url: /favicon\.ico
    static_files: staticfiles
    upload: favicon\.ico

  - url: /staticfiles
    static_dir: staticfiles

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
